Nothing:
Proxy txt@Text: #{txt}
Yes: Yes
No: No
Active: Active
Continue: Continue
Update: Update
Updated: Updated

HomeRBreadcrumb: Home
AuthRBreadcrumb: Login
SignoutRBreadcrumb: Signout
ProfileRBreadcrumb: Profile
CreateRBreadcrumb: New

HomeRTitle: Welcome | Lsp
SignoutRTitle: Logout | Lsp
ProfileRTitle usr@YesodUser: #{usr} | Lsp

Home: Home
Profile: Profile
Login: Login
Logout: Logout
Iso639v1: en
Iso3166v1: gb

ProfilePageGreet usr@YesodUser: You are logged in as #{usr}

Name: Name
Password: Password

HomeBigHeader: BtcLsp
HomeSmallHeader: Lightning Network Service Provider
