Nothing:
Proxy txt@Text: #{txt}
Yes: Да
No: Нет
Active: Активно
Continue: Продолжить
Update: Обновить
Updated: Обновлено
Copy: копировать

HomeRBreadcrumb: Главная
AuthRBreadcrumb: Войти
SignoutRBreadcrumb: Выйти
CreateRBreadcrumb: Создать
OpenChanRBreadcrumb: Открыть Канал

HomeRTitle: Добро пожаловать | ЛСП
SignoutRTitle: Выйти | ЛСП
OpenChanRTitle: Открыть Канал | ЛСП

Home: Главная
Login: Войти
Logout: Выйти
Iso639v1: ru
Iso3166v1: ru

Name: Имя
Password: Пароль

HomeBigHeader: БТК ЛСП
HomeSmallHeader: Сервис Провайдер Лайтнинг Сети

OpenChan: Открыть Канал
OpenChanInstruction: Чтобы открыть канал к ЛСП, отсканируйте QR код вашим лайтнинг кошельком или вручную скопируйте адрес лайтнинг ноды внизу.
