name:                btc-lsp
version:             0.1.0.0
github:              "githubuser/btc-lsp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/btc-lsp#readme>

flags:
  ghcid:
    manual: true
    default: false

default-extensions:
- NoImplicitPrelude
- MultiParamTypeClasses
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables
- DeriveGeneric
- GeneralizedNewtypeDeriving
- TupleSections
- DataKinds
- DerivingStrategies
- KindSignatures
- FlexibleContexts
- FlexibleInstances
- StrictData
- TypeFamilies
- TypeOperators
- StandaloneDeriving
- DerivingVia
- ExistentialQuantification
- InstanceSigs

ghc-options:
# For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
# Enable all warnings with -Weverything, then disable the ones we don’t care about
- -Weverything
- -Werror
- -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
- -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
- -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
- -Wno-all-missed-specialisations # See missed-specialisations
- -Wno-unsafe # Don’t use Safe Haskell warnings
- -Wno-safe # Don’t use Safe Haskell warnings
- -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
- -Wno-missing-export-lists # Because of proto-lens
when:
  - condition: impl(ghc >= 8.10.7)
    ghc-options:
    - -Wno-missing-safe-haskell-mode
    - -Wno-prepositive-qualified-module
    - -fenable-th-splice-warnings
    - -fprint-potential-instances

_deps: &deps
  dependencies:
  # foundation
  - base >= 4.7 && < 5
  - unliftio
  - universum
  - containers
  - transformers
  - extra
  - errors
  - witch
  # time
  - chronos
  - iso8601-time
  - unbounded-delays
  # storage
  - persistent >= 2.13.2.1
  - persistent-postgresql >= 2.13.2.1
  - persistent-migration
  - esqueleto >= 3.5.3
  # logging
  - katip
  - pretty
  - GenericPretty
  - generic-pretty-instances
  # lens
  - microlens
  # bytes
  - case-insensitive
  - bytestring
  - text
  - proto-lens
  - proto-lens-runtime
  - binary
  - casing
  - memory
  - base16-bytestring
  - hex-text
  - base64-bytestring >= 1.2.1
  - qrcode-juicypixels
  - qrcode-core
  - format-numbers
  # threads
  - async
  - stm
  - resource-pool
  # th
  - template-haskell
  # crypto
  - uuid
  - network-bitcoin
  - SHA
  - lnd-client
  - cryptonite
  - secp256k1-haskell
  # web
  - wai
  - warp
  - warp-tls
  - warp-grpc
  - http2
  - http2-grpc-types
  - http2-grpc-proto-lens
  - http2-client
  - http2-client-grpc
  - network
  # other
  - envparse
  - scientific
  - vector
  # yesod
  - yesod >=1.6 && <1.7
  - yesod-core >=1.6 && <1.7
  - yesod-auth >=1.6 && <1.7
  - yesod-static >=1.6 && <1.7
  - yesod-form >=1.6 && <1.7
    #- classy-prelude >=1.5 && <1.6
  - classy-prelude-yesod >=1.5 && <1.6
  - template-haskell
  - shakespeare >=2.0 && <2.1
  - hjsmin >=0.1 && <0.3
  - wai-extra >=3.1 && <3.2
  - yaml >=0.11 && <0.12
  - http-client-tls >=0.3 && <0.4
  - warp >=3.0 && <3.4
  - aeson >=1.4 && <1.6
  - monad-logger >=0.3 && <0.4
  - fast-logger >=2.2 && <3.1
  - file-embed
  - time
  - case-insensitive
  - wai

_ghcid: &ghcid
  when:
  - condition: flag(ghcid)
    then:
      <<: *deps
      source-dirs:
      - src
      ghc-options:
      - -Wno-unused-packages
    else:
      dependencies:
      - btc-lsp

_optimized: &optimized
  ghc-options:
  - -O2
  - -optc-O3
  - -funfolding-use-threshold=16
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -optl-fuse-ld=gold
  ld-options:
  - -fuse-ld=gold

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  <<: *deps
  source-dirs:
  - src
  ghc-options:
  - -fwarn-tabs
  - -O2

executables:
  btc-lsp-exe:
    main: Main.hs
    dependencies:
    - base
    source-dirs:
    - app
    <<: *optimized
    <<: *ghcid
  btc-lsp-integration:
    main: Integration.hs
    dependencies:
    - base
    - witch
    - lnd-client
    - envparse
    - network-bitcoin
    - unliftio
    - proto-lens
    - aeson
    - bytestring
    - vector
    - QuickCheck
    - hspec
    source-dirs:
    - integration
    - test
    ghc-options:
    - -O2
    - -optc-O3
    - -funfolding-use-threshold=16
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is
    - Integration
    - -optl-fuse-ld=gold
    ld-options:
    - -fuse-ld=gold
    <<: *ghcid
  btc-lsp-prof:
    main: Main.hs
    dependencies:
    - base
    source-dirs:
    - app
    ghc-options:
    - -O2
    - -optc-O3
    - -funfolding-use-threshold=16
    - -threaded
    - -prof
    - -fprof-auto
    - "\"-with-rtsopts=-N -s -p -h -xt\""
    - -fexternal-interpreter
    - -optl-fuse-ld=gold
    ld-options:
    - -fuse-ld=gold
    <<: *ghcid

tests:
  btc-lsp-test:
    main: Main.hs
    dependencies:
    - base
    - witch
    - lnd-client
    - envparse
    - network-bitcoin
    - unliftio
    - proto-lens
    - aeson
    - bytestring
    - vector
    - QuickCheck
    - hspec
    source-dirs:
    - test
    <<: *optimized
    <<: *ghcid
