deployment:
  bitcoindSecretEnv:
    - name: BITCOIN_RPCUSER
      valueFrom:
        secretKeyRef:
          key: bitcoind_rpcuser
          name: bitcoind-secret
    - name: BITCOIN_RPCPASS
      valueFrom:
        secretKeyRef:
          key: bitcoind_rpcpassword
          name: bitcoind-secret

secret:
  data:
    bitcoind_rpcuser: null
    bitcoind_rpcpassword: null
    lnd_hex_macaroon: ${LND_ALICE_HEX_MACAROON}
    lnd_tls_cert: ${LND_ALICE_TLS_CERT}
