deployment:
  lndSecretEnv:
    - name: LND_HEX_MACAROON
      valueFrom:
        secretKeyRef:
          key: lnd_hex_macaroon
          name: lnd-secret
    - name: LND_ALICE_HEX_MACAROON
      valueFrom:
        secretKeyRef:
          key: lnd_hex_macaroon
          name: lnd-alice-secret
    - name: LND_BOB_HEX_MACAROON
      valueFrom:
        secretKeyRef:
          key: lnd_hex_macaroon
          name: lnd-bob-secret
  env:
    - name: RTL_CONFIG_NODES_JSON
      value: '[
        {
          "hexMacaroon": "$(LND_HEX_MACAROON)",
          "index": 1,
          "lnServerUrl": "https://lnd-private-service.default.svc.cluster.local:8080" 
        },
        {
          "hexMacaroon": "$(LND_ALICE_HEX_MACAROON)",
          "index": 2,
          "lnServerUrl": "https://lnd-alice-private-service.default.svc.cluster.local:8080" 
        },
        {
          "hexMacaroon": "$(LND_BOB_HEX_MACAROON)",
          "index": 3,
          "lnServerUrl": "https://lnd-bob-private-service.default.svc.cluster.local:8080" 
        }
      ]'

secret: 
  data:
    lnd_hex_macaroon: null
