name: release
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Ensure cache dir exists
      run: |
        whoami
        mkdir -p /tmp/nix_ci_cache
        sudo chown -R $USER:$USER /tmp/nix_ci_cache
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: github_action_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }}
        if_key_exists: fail
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.11
        extra_nix_config: |
          system-features = kvm
          http2 = false
          require-sigs = false
          sandbox = false
          cores = 2
          max-jobs = 4
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://cache.nixos.org file:///tmp/nix_ci_cache https://cache.iog.io ssh://nix-ssh@nixos.dev.testenv.io?ssh-key=/home/runner/.ssh/github_action_ed25519
          trusted-substituters = file:///tmp/nix_ci_cache ssh://nix-ssh@nixos.dev.testenv.io?ssh-key=/home/runner/.ssh/github_action_ed25519
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          trusted-users = nix-ssh
          post-build-hook = ${{ github.workspace }}/nix/upload-to-cache.sh
    - uses: actions/cache@v3
      with:
        path: /tmp/nix_ci_cache
        key: cache-${{ runner.os }}-${{ matrix.configuration }}-${{ github.sha }}
        restore-keys: cache-${{ runner.os }}-${{ matrix.configuration }}-
    - name: Test all
      run: |
        whoami
        which nix
        mkdir -p ${{ github.workspace }}/logs
        chmod -R 777 ${{ github.workspace }}/logs
        logsdir="${{ github.workspace }}/logs"
        sudo cp /home/runner/.ssh/config /etc/ssh/ssh_config.d/coinix.conf
        sudo echo "$HOME"
        export NIX_SSHOPTS="-i /home/runner/.ssh/github_action_ed25519"
        nix store ping --store ssh://nix-ssh@nixos.dev.testenv.io
        nix store ping --store ssh://cache_coinix
        nix-build --option sandbox false --show-trace --pure ./test.nix --argstr log "$logsdir"
        ./result/bin/all-tests
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-logs
        path: ${{ github.workspace }}/logs/
    - name: Release all
      run: ./nix/ci-release.sh
    - name: Create github release
      if: github.ref_type == 'tag'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Docker login
      if: github.ref_type == 'tag'
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push
      if: github.ref_type == 'tag'
      run: ./nix/ci-push.sh
    - name: Upload btc-lsp docker image
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-btc-lsp.tar.gz
        asset_name: docker-image-btc-lsp.tar.gz
        asset_content_type: application/gzip
    - name: Upload btc-lsp docker image version
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-btc-lsp.txt
        asset_name: docker-image-btc-lsp.txt
        asset_content_type: text/plain
    - name: Upload integration docker image
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-integration.tar.gz
        asset_name: docker-image-integration.tar.gz
        asset_content_type: application/gzip
    - name: Upload integration docker image version
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-integration.txt
        asset_name: docker-image-integration.txt
        asset_content_type: text/plain
    - name: Upload electrs docker image
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./electrs-client/build/docker-image-electrs.tar.gz
        asset_name: docker-image-electrs.tar.gz
        asset_content_type: application/gzip
    - name: Upload electrs docker image version
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./electrs-client/build/docker-image-electrs.txt
        asset_name: docker-image-electrs.txt
        asset_content_type: text/plain
