name: release
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ./nix.tar.gz
        key: ${{ runner.os }}-nix-v5
        restore-keys: |
          ${{ runner.os }}-nix-v4
          ${{ runner.os }}-nix-
    - name: Restore cache
      run: |
        docker run --rm \
          -v nix-$USER:/nix \
          -v $(pwd):/app \
          -w /app nixos/nix:2.3.12 \
          sh -c "tar -xvzf ./nix.tar.gz -C /" \
        || true
    - name: Release all
      run: ./nix/ci-release.sh
    - name: Create github release
      if: github.ref_type == 'tag'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Docker login
      if: github.ref_type == 'tag'
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push
      if: github.ref_type == 'tag'
      run: ./nix/ci-push.sh
    - name: Upload btc-lsp docker image
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-btc-lsp.tar.gz
        asset_name: docker-image-btc-lsp.tar.gz
        asset_content_type: application/gzip
    - name: Upload btc-lsp docker image version
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-btc-lsp.txt
        asset_name: docker-image-btc-lsp.txt
        asset_content_type: text/plain
    - name: Upload electrs docker image
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-electrs.tar.gz
        asset_name: docker-image-electrs.tar.gz
        asset_content_type: application/gzip
    - name: Upload electrs docker image version
      if: github.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./btc-lsp/build/docker-image-electrs.txt
        asset_name: docker-image-electrs.txt
        asset_content_type: text/plain
    - name: Save cache
      run: |
        docker run --rm \
          -v nix-$USER:/nix \
          -v $(pwd):/app \
          -w /app nixos/nix:2.3.12 \
          sh -c "tar -czvf ./nix.tar.gz /nix/*"
